import type { ColumnDef } from "@tanstack/react-table";
import { useMemo } from "react";
import type { AiUsageBreakdownItem, AiUsageSummary, ReportAiUsageProjectSummary } from "@git-snitch/core";

import { EmptyState } from "./empty-state.js";
import { Section, SectionHeader, SectionStat } from "./section.js";
import { DataTable } from "./tables.js";

type AiUsagePanelProps = {
  readonly title?: string;
  readonly description?: string;
  readonly usage: AiUsageSummary | ReportAiUsageProjectSummary;
};

function formatNumber(value: number) {
  return new Intl.NumberFormat("en").format(value);
}

export function formatAiUsageCost(value: number) {
  return new Intl.NumberFormat("en", { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value);
}

export function formatAiUsageTokens(value: number) {
  return new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 }).format(value);
}

function hasBreakdowns(usage: AiUsageSummary | ReportAiUsageProjectSummary): usage is ReportAiUsageProjectSummary {
  return "breakdowns" in usage;
}

function usageHasTotals(usage: AiUsageSummary) {
  return usage.records > 0 || usage.tokens.total > 0 || usage.cost > 0 || (usage.unsubsidizedCost ?? 0) > 0;
}

function AiCostValue({ usage }: { readonly usage: AiUsageSummary }) {
  if (usage.unsubsidizedCost === undefined) {
    return formatAiUsageCost(usage.cost);
  }

  return (
    <span className="flex flex-col gap-1">
      <span>{formatAiUsageCost(usage.unsubsidizedCost)}</span>
      <span className="text-sm font-medium text-muted-foreground">Recorded: {formatAiUsageCost(usage.cost)}</span>
    </span>
  );
}

const breakdownColumns: ColumnDef<AiUsageBreakdownItem>[] = [
  { accessorKey: "key", header: "Name", cell: ({ row }) => <span className="font-medium text-foreground">{row.original.key}</span> },
  { accessorKey: "tokens.total", header: "Total", cell: ({ row }) => formatAiUsageTokens(row.original.tokens.total) },
  { accessorKey: "records", header: "Messages", cell: ({ row }) => formatNumber(row.original.records) },
  { accessorKey: "tokens.input", header: "Input", cell: ({ row }) => formatAiUsageTokens(row.original.tokens.input) },
  { accessorKey: "tokens.output", header: "Output", cell: ({ row }) => formatAiUsageTokens(row.original.tokens.output) },
  { id: "cache", header: "Cache", cell: ({ row }) => formatAiUsageTokens(row.original.tokens.cacheRead + row.original.tokens.cacheWrite) },
  { accessorKey: "tokens.reasoning", header: "Reasoning", cell: ({ row }) => formatAiUsageTokens(row.original.tokens.reasoning) },
  { accessorKey: "cost", header: "Recorded cost", cell: ({ row }) => formatAiUsageCost(row.original.cost) },
  { accessorKey: "unsubsidizedCost", header: "Unsubsidized cost", cell: ({ row }) => row.original.unsubsidizedCost === undefined ? "—" : formatAiUsageCost(row.original.unsubsidizedCost) },
];

function BreakdownTable({ title, rows, emptyDescription }: { readonly title: string; readonly rows: readonly AiUsageBreakdownItem[]; readonly emptyDescription: string }) {
  const columns = useMemo(() => breakdownColumns, []);

  return (
    <DataTable
      ariaLabel={title}
      data={rows}
      columns={columns}
      search={{ placeholder: "Search", toText: (row) => row.key }}
      exportConfig={{
        filename: `${title.toLowerCase().replace(/\s+/g, "-")}.csv`,
        mapRow: (row) => ({
          name: row.key,
          messages: row.records,
          inputTokens: row.tokens.input,
          outputTokens: row.tokens.output,
          cacheTokens: row.tokens.cacheRead + row.tokens.cacheWrite,
          reasoningTokens: row.tokens.reasoning,
          totalTokens: row.tokens.total,
          recordedCost: row.cost,
          unsubsidizedCost: row.unsubsidizedCost ?? "",
        }),
      }}
      emptyState={{ title: `${title} unavailable`, description: emptyDescription }}
    />
  );
}

export function AiUsagePanel({
  title = "AI usage",
  description = "Local assistant usage matched to this report. Workspace paths are not rendered in the HTML report.",
  usage,
}: AiUsagePanelProps) {
  const hasTotals = usageHasTotals(usage);

  return (
    <Section ariaLabel={title}>
      <SectionHeader title={title} description={description} />
      <div className="grid grid-flow-dense gap-3 sm:grid-cols-3 lg:grid-cols-6">
        <SectionStat label="Input tokens" value={formatNumber(usage.tokens.input)} description="Prompt and context tokens sent to the model." />
        <SectionStat label="Output tokens" value={formatNumber(usage.tokens.output)} description="Completion tokens generated by the model." />
        <SectionStat label="Cache tokens" value={formatNumber(usage.tokens.cacheRead + usage.tokens.cacheWrite)} description="Tokens served from cache (read + write)." />
        <SectionStat label="Total tokens" value={formatNumber(usage.tokens.total)} description="Sum of input, output, cache, and reasoning tokens." />
        <SectionStat
          label="AI cost"
          value={<AiCostValue usage={usage} />}
          description={usage.unsubsidizedCost === undefined ? "USD recorded or derived from local logs." : "Public model-price estimate with recorded log cost below."}
        />
        <SectionStat label="Messages" value={formatNumber(usage.records)} description="Matched assistant usage records." />
      </div>

      {!hasTotals ? (
        <EmptyState
          title="No AI usage matched this report"
          description="AI usage collection was enabled, but the matched local logs contain zero messages, tokens, and cost for this report scope."
        />
      ) : null}

      {hasBreakdowns(usage) ? (
        <div className="grid grid-flow-dense gap-4 xl:grid-cols-3">
          <BreakdownTable title="Client breakdown" rows={usage.breakdowns.byClient} emptyDescription="No client-level AI usage rows were available." />
          <BreakdownTable title="Model breakdown" rows={usage.breakdowns.byModel} emptyDescription="No model-level AI usage rows were available." />
          <BreakdownTable title="Recent days" rows={usage.breakdowns.byDay} emptyDescription="No dated AI usage rows were available." />
        </div>
      ) : null}
    </Section>
  );
}
